
######################################
### Configure programming language ###
######################################
language: java

##################################
### Make sure using Oracle JDK ###
##################################
jdk:
  - oraclejdk13

###################################
### Disable Email notifications ###
###################################
notifications:
  email: false

###############
### Caching ###
###############
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

#################
### SonarQube ###
#################
addons:
  sonarcloud:
    organization: "mysteryworlds"
    token:
      secure: iqUOCwvRsZlgaq7rh8E++Ees06KqGNS6hUxN1lCOcR2oj/aGbFrY1noHPI4115FE56Azjf4Ow4aiHh+mws3BiPGZrOBoS1PuQnr+1Zm1h+an2iOVJqdBegM0UMfYlMfCG96F/RH38cO4NDaa4+XPkdz7Yn6PAg8RwNiXR1GqnEMsWJI2hG/vvFEYxPaBcTPP4lZ+c5F25jlS7S3Et9LuyumtSBWyaUGhHWtcSolTMBDFIMzxE+jVtrX0M6D4ZiDgabvuOumyLBw+jTJLTOHZofHUyxLx9Pa72UxuvCEHCWokIEPLkpy/POvrYgCf4f5trEcQ1edi3EvPt/RtugXwa4DoILbNRReMZXa7ASgwARcc5MXR2++1D/GdLYRRPyyGRO6eNfc3L9RQ6fH8iygR3gn4t6TERG/emoUu4PQe3vrAbDb0OTlr4f1kToi8bJpYUezjl4Dp5ja0/NcMVlM1ZUje6D/gASqmLL1pQgM6bJkpVjrqce5cGzbXqOpsbmKvpIdO2nv8RtaluXZJH2BOEWgvauOz/DickpqhP+KMa/RW1N0ZmkqdKKE4B8NusZN7b/28Vh9uwQvUtyvNOxBfrFCzD18M2Oh5Ozj3pQOUZkeXpYBN4hKL9QyJXlwxiJyq0TlvtZvuqT0qwOd38nI0QUS1CGFctwKc9NWN2YbNec8=

###########################
### Actual Build Script ###
###########################
script:
  - ./gradlew build check codeCoverageReport --scan -s
  - ./gradlew sonarqube

##################
### Deployment ###
##################
deploy:
  provider: script
  script: ./gradlew publish
  on:
    tags: true